name: Simple CI/CD with Environment

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo a simple message
        run: echo "Build step completed."

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        environment: [ 'dev', 'int', 'prd' ]
    steps:
      - name: Echo deploy message
        run: |
          echo "Deploying to ${{ matrix.environment }} environment."
          if [ "${{ matrix.environment }}" = "dev" ] || [ "${{ github.event_name }}" = "schedule" ]; then
            echo "This is a dev environment or a scheduled run."
            # Add your deployment steps for dev environment here
          else
            echo "This is a test environment."
            # Add your deployment steps for test environment here
          fi
