name: Simple CI/CD with Environment

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo a simple message
        run: echo "Build and push step completed."

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        environment: ['dev', 'int', 'prd'] 
    steps:
      - name: Echo deploy message for dev or scheduled runs
        if: matrix.environment == 'dev' || github.event_name == 'schedule'
        run: |
          echo "Deploying to ${{ matrix.environment }} environment. This is a dev environment or a scheduled run."
          # Add your deployment steps for the dev environment or scheduled runs here

      - name: Setup deployment for int and prd environments
        if: matrix.environment != 'dev'
        run: |
          echo "Setup for deployment to ${{ matrix.environment }}. Awaiting approval."
          # This step can be used to setup or pre-configure deployment without actually deploying

    # Conditional environment assignment with manual approval for int and prd
    environment:
      name: ${{ matrix.environment }}
      # Requires setting up environment protection rules in GitHub for int and prd to require manual approval
