name: Simple CI/CD with Environment

on:
  schedule:
    - cron: '0 22 * * *' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo a simple message
        run: echo "Build and push step completed."

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push 
    steps:
      - name: Echo deploy message for dev or scheduled runs
        run:   echo "Deploying to 'dev' environment. This is a dev environment or a scheduled run."

    environment:
      name: "dev"
